---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kepler-exporter
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: kepler-exporter
        volumeMounts:
         -  mountPath: /var/scaphandre/
            name: scaphandre
            readOnly: true